[package]
name = "simple-mp3-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
relm4 = { version = "0.9.1", features = ["libadwaita"] }
libadwaita = { version = "0.7.2", features = ["v1_6"] }
sysinfo = "0.33.1"
