name: Build Windows Release
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-win-release:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-glib2 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-libadwaita mingw-w64-ucrt-x86_64-python-mingw-ldd
        id: msys2
      - name: Adding msys2 bins to path
        run: Add-Content $env:GITHUB_PATH "${{ steps.msys2.outputs.msys2-location }}\ucrt64\bin"
      - name: Update rustup
        run: rustup update
      - name: Build the app
        run: cargo build -r
      - name: Create build dir
        run: |
          mkdir build
          mkdir build/dlls
          mkdir build/lib
          mkdir -p build/share/icons/hicolor
          mkdir -p build/share/icons/Adwaita
          cp ./target/release/simple-mp3-downloader.exe ./build/
      - name: Copy dependencies & required files
        run: |
          set MSYSTEM=UCRT64
          msys2 -c 'ldd "./build/simple-mp3-downloader.exe" | grep "/ucrt64\/bin\/.*dll" -o | xargs -I % cp -f % "./build/dlls/"'
          cp -r ${{ steps.msys2.outputs.msys2-location }}/ucrt64/lib/gdk-pixbuf-2.0 ./build/libs/lib/
          cp ${{ steps.msys2.outputs.msys2-location }}/ucrt64/share/icons/hicolor/index.theme ./build/share/icons/hicolor/
          cp ${{ steps.msys2.outputs.msys2-location }}/ucrt64/share/icons/Adwaita/index.theme ./build/share/icons/Adwaita/
          cp ${{ steps.msys2.outputs.msys2-location }}/ucrt64/share/icons/Adwaita/icon-theme.cache ./build/share/icons/Adwaita/
          cp -r ${{ steps.msys2.outputs.msys2-location }}/ucrt64/share/icons/Adwaita/scalable ./build/share/icons/Adwaita/
      - name: Create the installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: ./win-setup.iss
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/setup/setup.exe

