name: Build Windows Release
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-win-release:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-glib2 mingw-w64-ucrt-x86_64-pkg-config mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-libadwaita mingw-w64-ucrt-x86_64-python-mingw-ldd
        id: msys2
      - name: Update rustup
        run: rustup update
      - env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: set PATH=%PATH%;${MSYS2_LOCATION}\ucrt64\bin && cargo build -r
      - name: Create build dir
        run: mkdir build && cp ./target/release/simple-mp3-downloader.exe ./build/
      - name: Copy dependencies
        run: msys2 -c 'ldd "./build/simple-mp3-downloader.exe" | grep "$MSYSTEM_PREFIX\/bin\/.*dll" -o | xargs -I{} cp -f "{}" "./build/"'
      - name: Compress build
        run: powershell Compress-Archive -Path ".\build" -DestinationPath ".\build.zip"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: .\build.zip

